version: '3.8'

services:
  qb-autogen-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    volumes:
      - .:/app
      - /app/.venv
    command: ["python", "run.py"]
    ports:
      - "5000:5000"